baseURL = "https://miry1919.github.io/hugosite/"
publishDir = "docs"
languageCode = "en-us"
title = "Hello"
theme = "minimal"

[params]
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/podcast/"
    name = "Podcasts"
    weight = 4
    
[[menu.main]]
    url = "/books/"
    name = "Books"
    weight = 5
    
[[menu.main]]
    url = "/quote/"
    name = "Quotes"
    weight = 6
    
[[menu.main]]
    url = "/music/"
    name = "Music"
    weight = 7
    
[[menu.main]]
url = "/sport/"
name = "Sport"
weight = 8

[[menu.main]]
url = "/food/"
name = "Food"
weight = 9

[[menu.icon]]
    url = "https://twitter.com/Miry1919/"
    name = "twitter"
    weight = 1
